[server]
address = ":8000"
use_https = false
enable_cors = false

[auth]
enabled = false
type = "jwt"

[storage]
rules_path = "./conditions/v1"
remote_configuration = "./conditions/v2"
cluster_mapping = "cluster-mapping.json"

[sentry]
dsn = "https://daca7436565e4580a85102b9ede9a177@sentry.devshift.net/1020"
environment = "dev"

[logging]
debug = true
log_level = "debug"
use_stderr = true
logging_to_cloud_watch_enabled = false
logging_to_sentry_enabled = true
logging_to_kafka_enabled = false

[kafka_zerolog]
broker = ""
topic = ""
cert_path = ""
level = ""

[cloudwatch]
aws_access_id = "a key id"
aws_secret_key = "tshhhh it is a secret"
aws_session_token = ""
aws_region = "us-east-1"
log_group = "platform-dev"
stream_name = "io-gathering-service"
debug = false
create_stream_if_not_exists = false
