{
 "title": "CCX Gathering Service",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "ccx-data-pipeline-stage,ccx-data-pipeline-prod"
   }
  ]
 },
 "panels": [
  {
   "title": "Pods CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=\"$namespace\",pod=~\"io-gathering-service-instance-.*\"}[1m])) by (pod)\n"
    }
   ]
  },
  {
   "title": "Pods memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{namespace=\"$namespace\",pod=~\"io-gathering-service-instance-.*\"}) by (pod)"
    }
   ]
  },
  {
   "title": "Pods network in",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"io-gathering-service-instance-.*\"}[1m])) by (pod)"
    }
   ]
  },
  {
   "title": "Pods network out",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"io-gathering-service-instance-.*\"}[1m])) by (pod)"
    }
   ]
  }
 ]
}