name: Go linters

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  golint:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go-version:
          - "1.20"
          - "1.21"
    name: Linters for Go ${{ matrix.go-version}}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Build project
        run: go build
      - name: GO formatting
        run: make fmt
      - name: GO lint 
        run: make lint
      - name: GO vet
        run: make vet
      - name: gocyclo
        run: make cyclo
      - name: shellcheck
        run: make shellcheck
      - name: errcheck
        run: make errcheck
      - name: goconst checker
        run: make goconst
      - name: gosec checker
        run: make gosec
      - name: ineffassign checker
        run: make ineffassign
      - name: ABC metrics checker
        run: make abcgo
      - name: Check configuration
        run: make check-config
